# Generated by Django 6.0 on 2026-06-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Live Service', max_length=255)),
                ('stream_url', models.URLField(help_text='Facebook Live, YouTube Live, Vimeo embed URL')),
                ('is_active', models.BooleanField(default=False)),
                ('platform', models.CharField(blank=True, help_text='facebook, youtube, vimeo', max_length=50, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
