# Generated by Django 6.0 on 2026-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('speaker', models.CharField(blank=True, max_length=255)),
                ('preached_on', models.DateField()),
            ],
        ),
    ]
