# Generated by Django 6.0 on 2026-06-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sermon_thumbnails/'),
        ),
    ]
