# Generated by Django 6.0 on 2026-06-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0002_sermon_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Facebook Live, Vimeo, etc.', null=True),
        ),
    ]
