# Generated by Django 6.0 on 2026-06-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0003_sermon_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='live_url',
            field=models.URLField(blank=True, help_text='YouTube Live, Facebook Live, Vimeo, or embed link', null=True),
        ),
    ]
