# Generated by Django 6.0 on 2025-12-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='none yet', max_length=500),
            preserve_default=False,
        ),
    ]
