# Generated by Django 6.0 on 2026-06-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_end_time_service_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='start_date',
        ),
    ]
