# Generated by Django 6.0 on 2026-06-07 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('services', '0005_remove_service_end_date_remove_service_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='services.service'),
        ),
    ]
