# Generated by Django 6.0 on 2026-06-07 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_service'),
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='service',
        ),
        migrations.AddField(
            model_name='media',
            name='sermon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='sermons.sermon'),
        ),
    ]
